"""empty message

Revision ID: 5a37a70ada22
Revises: 
Create Date: 2018-10-08 20:42:20.473303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a37a70ada22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('beans', sa.Float(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'beans')
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
