"""empty message

Revision ID: 6dd8acca2063
Revises: e96a32dad58d
Create Date: 2018-10-08 22:08:07.019566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd8acca2063'
down_revision = 'e96a32dad58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('wish', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
