"""empty message

Revision ID: e274098fdc01
Revises: 5a37a70ada22
Create Date: 2018-10-08 22:06:29.352515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e274098fdc01'
down_revision = '5a37a70ada22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('wish', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
